project_id = "gcxqcxrshrfzuhyhfciv"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "https://leul-dev.lovable.app"
additional_redirect_urls = ["https://leul-dev.lovable.app"]
jwt_expiry = 3600
enable_signup = true

[functions.send-email-reply]
verify_jwt = false