// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gcxqcxrshrfzuhyhfciv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjeHFjeHJzaHJmenVoeWhmY2l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDU1NTIsImV4cCI6MjA2NDM4MTU1Mn0.1haevjOmhVRWqcu10SEIQBVmPW-VwxNAiFxlHKRG_qU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});